wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702836832.599527
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      4: 3.10.5
      5: 0.15.12
      8:
      - 3
      - 8
      13: windows-amd64
